#!/usr/bin/env python3
"""Generate `context/components.md` from the tree.

Structural facts rot when they are written by hand and changed by code. This
extractor derives the component map from the repository itself, so the map
cannot drift: every skill, agent, command, hook event, script and template is
discovered, not listed.

The one thing not derivable from the tree is which loop station a skill serves -
that is a fact about the design, not about the files - so it is declared here,
in the generator, and the generator **fails** if a skill is missing from the
declaration. A new skill therefore cannot be added without deciding where in the
loop it belongs, which is the correct forcing function.

Deterministic: sorted iteration, no clock, no absolute paths.

Usage:
    python scripts/extract_components.py            # dry run
    python scripts/extract_components.py --write    # write the map
    python scripts/extract_components.py --check    # exit 1 if drifted
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

GENERATOR = "scripts/extract_components.py"
TARGET = "context/components.md"

# Which loop station each skill serves. Declared, not derived - see the module
# docstring. A skill absent from this map is an error, not a default.
STATIONS: dict[str, str] = {
    "akinator": "master",
    "akinator-intake": "1 ASK",
    "akinator-audit": "3 AUDIT",
    "akinator-plan": "4 PLAN",
    "akinator-document-change": "6 DOCUMENT",
    "akinator-business-map": "6 DOCUMENT",
    "akinator-product-map": "6 DOCUMENT",
    "akinator-ops-map": "6 DOCUMENT",
    "akinator-adr": "6 DOCUMENT",
    "akinator-skillify": "7 SKILLIFY",
    "akinator-rule-forge": "8 RULE",
    "akinator-contextify": "9 CONTEXTIFY",
    "akinator-memoize": "10 MEMOIZE",
    "akinator-index-sync": "11 INDEX",
    "akinator-router-sync": "11 SYNC",
    "akinator-gate-economy": "12 VERIFY",
    "akinator-coverage": "12 VERIFY",
    "akinator-resource-guard": "discipline",
    "akinator-anti-gaming": "discipline",
    "akinator-onboard": "install",
}


def banner() -> str:
    return (
        "<!--\n"
        "GENERATED FILE - DO NOT EDIT BY HAND.\n"
        f"Generated by `{GENERATOR}`. Edit the extractor, then regenerate with:\n"
        f"    python {GENERATOR} --write\n"
        "-->\n"
    )


def frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    out: dict[str, str] = {}
    key: str | None = None
    for line in text[4:end].splitlines():
        if line and not line[0].isspace() and ":" in line:
            key, _, value = line.partition(":")
            key = key.strip()
            out[key] = value.strip()
        elif key and line.strip():
            out[key] = (out[key] + " " + line.strip()).strip()
    return out


def first_sentence(text: str, limit: int = 140) -> str:
    text = text.replace("|", "/").strip()
    for end in (". ", ".\n"):
        if end in text:
            text = text.split(end, 1)[0] + "."
            break
    if len(text) > limit:
        text = text[: limit - 1].rsplit(" ", 1)[0] + "..."
    return text


def render(repo: Path) -> str:
    skills = sorted((repo / "skills").glob("*/SKILL.md"))
    agents = sorted((repo / "agents").glob("*.md"))
    commands = sorted((repo / "commands").glob("*.md"))
    templates = sorted(
        p for p in (repo / "templates").glob("*.md")
        if p.name.lower() != "readme.md"
    )
    scripts = sorted(
        p for p in (repo / "scripts").iterdir()
        if p.is_file() and p.suffix in (".py", ".sh", ".ps1")
    )

    undeclared = sorted({p.parent.name for p in skills} - set(STATIONS))
    if undeclared:
        raise SystemExit(
            f"{GENERATOR}: these skills have no declared loop station: "
            f"{', '.join(undeclared)}\n"
            "Add them to STATIONS - a skill must belong somewhere in the loop."
        )

    lines: list[str] = [banner()]
    lines.append("# Component map")
    lines.append("")
    lines.append(
        "Every component this plugin ships, where it lives, and which platform"
    )
    lines.append("reads it.")
    lines.append("")
    lines.append("## Scope")
    lines.append("")
    lines.append(
        "- **Covers:** the plugin's own components - skills, agents, commands,"
    )
    lines.append(
        "  hooks, scripts and templates - and which platform surface each serves."
    )
    lines.append(
        "- **Does not cover:** what each component *does*. That is"
    )
    lines.append(
        "  `docs/skills.md`, `docs/architecture.md`, and the components"
    )
    lines.append("  themselves.")
    lines.append("")

    # -- skills -------------------------------------------------------------
    lines.append(f"## Skills - {len(skills)}")
    lines.append("")
    lines.append(
        "Read by Claude Code from `skills/`, and by Codex from the generated"
    )
    lines.append("`.agents/skills/`. `skills/` is canonical.")
    lines.append("")
    lines.append("| Skill | Loop station | Trigger |")
    lines.append("|---|---|---|")
    for path in skills:
        name = path.parent.name
        meta = frontmatter(path)
        lines.append(
            f"| `{name}` | {STATIONS[name]} | "
            f"{first_sentence(meta.get('description', ''))} |"
        )
    lines.append("")

    # -- agents -------------------------------------------------------------
    lines.append(f"## Agents - {len(agents)}")
    lines.append("")
    lines.append(
        "Read by Claude Code from `agents/`. Codex has no equivalent subagent"
    )
    lines.append("surface; the same review lenses are applied inline there.")
    lines.append("")
    lines.append("| Agent | Reviews for |")
    lines.append("|---|---|")
    for path in agents:
        meta = frontmatter(path)
        lines.append(
            f"| `{path.stem}` | {first_sentence(meta.get('description', ''))} |"
        )
    lines.append("")

    # -- commands -----------------------------------------------------------
    lines.append(f"## Commands - {len(commands)}")
    lines.append("")
    lines.append("Read by Claude Code from `commands/`.")
    lines.append("")
    lines.append("| Command | Arguments |")
    lines.append("|---|---|")
    for path in commands:
        meta = frontmatter(path)
        hint = meta.get("argument-hint", "").replace("|", "/")
        lines.append(f"| `/{path.stem}` | `{hint}` |")
    lines.append("")

    # -- hooks --------------------------------------------------------------
    hooks_path = repo / "hooks" / "hooks.json"
    events: list[tuple[str, str]] = []
    if hooks_path.is_file():
        data = json.loads(hooks_path.read_text(encoding="utf-8"))
        for event, entries in sorted(data.get("hooks", {}).items()):
            for entry in entries:
                for hook in entry.get("hooks", []):
                    events.append((event, hook.get("command", "")))

    lines.append(f"## Hooks - {len(events)}")
    lines.append("")
    lines.append(
        "Read by Claude Code from `hooks/hooks.json`. Codex plugin validation"
    )
    lines.append(
        "rejects a `hooks` field in its manifest, so this surface is"
    )
    lines.append(
        "Claude-only; the same contract reaches Codex through the generated"
    )
    lines.append("`AGENTS.md`.")
    lines.append("")
    lines.append("| Event | Command |")
    lines.append("|---|---|")
    for event, command in events:
        lines.append(f"| `{event}` | `{command}` |")
    lines.append("")

    # -- scripts ------------------------------------------------------------
    lines.append(f"## Scripts - {len(scripts)}")
    lines.append("")
    lines.append("| Script | Purpose |")
    lines.append("|---|---|")
    for path in scripts:
        lines.append(f"| `scripts/{path.name}` | {_script_purpose(path)} |")
    lines.append("")

    # -- templates ----------------------------------------------------------
    lines.append(f"## Templates - {len(templates)}")
    lines.append("")
    lines.append(
        "What Akinator writes into target repositories. Every template ships a"
    )
    lines.append("filled example.")
    lines.append("")
    lines.append("| Template | Filled example |")
    lines.append("|---|---|")
    for path in templates:
        example = repo / "templates" / "examples" / path.name
        marker = (
            f"`templates/examples/{path.name}`" if example.is_file() else "**MISSING**"
        )
        lines.append(f"| `templates/{path.name}` | {marker} |")
    lines.append("")

    # -- staleness ----------------------------------------------------------
    lines.append("## Regenerate when")
    lines.append("")
    lines.append(f"- Extractor: `{GENERATOR}`")
    lines.append(f"- Regenerate with: `python {GENERATOR} --write`")
    lines.append(
        f"- Drift check: `python {GENERATOR} --check` in CI - regenerates in"
    )
    lines.append("  memory and diffs; exits non-zero if they differ.")
    lines.append(
        "- Regenerate when: a skill, agent, command, hook, script or template is"
    )
    lines.append("  added, removed or renamed.")
    lines.append("")
    lines.append("## Related")
    lines.append("")
    lines.append(
        "- Docs: `docs/architecture.md` - what these components do and how they"
    )
    lines.append("  interact")
    lines.append(
        "- Docs: `docs/compatibility.md` - the platform contracts each surface"
    )
    lines.append("  relies on")
    lines.append("- Skills: `docs/skills.md` - the skills index")
    lines.append("")
    return "\n".join(lines)


def _script_purpose(path: Path) -> str:
    """The first line of the script's docstring or header comment."""
    text = path.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith('"""'):
            return first_sentence(stripped.strip('"').strip(), 100)
        if stripped.startswith("# ") and "!/" not in stripped:
            return first_sentence(stripped[2:].strip(), 100)
        if stripped.startswith(".SYNOPSIS"):
            continue
        if stripped and stripped.startswith("Install the Akinator"):
            return first_sentence(stripped, 100)
    return "(no description)"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="extract_components")
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    repo = Path(args.root).resolve()
    if not (repo / "skills").is_dir():
        print(f"no skills/ directory under {repo}", file=sys.stderr)
        return 2

    desired = render(repo)
    target = repo / TARGET
    current = (
        target.read_text(encoding="utf-8") if target.is_file() else None
    )

    if args.write:
        if current == desired:
            print(f"{TARGET} already up to date")
            return 0
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(desired, encoding="utf-8", newline="\n")
        print(f"wrote {TARGET}")
        return 0

    if current == desired:
        print(f"{TARGET} matches the tree.")
        return 0

    print(f"{TARGET} is drifted." if current else f"{TARGET} is missing.")
    print(f"Fix with: python {GENERATOR} --write")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
